export const ROUTES = {
  home: "/",
  cost: "/임신중절수술-비용",
  recovery: "/임신중절수술-회복기간",
  precautions: "/임신중절수술-주의사항",
  hospital: "/임신중절수술-병원-선택",
  reviews: "/임신중절수술-후기",
  faq: "/임신중절수술-자주-묻는-질문",
  preExam: "/임신중절수술-전-검사",
  earlyGestation: "/임신초기중절수술-주수-확인",
  dayProcedure: "/임신중절수술-당일-절차",
  sleepAnesthesia: "/임신중절수술-수면마취",
  procedureMethods: "/흡입술과-소파술-차이",
  afterSymptoms: "/임신중절수술-후-이상증상",
  afterDailyLife: "/임신중절수술-후-일상활동",
  bookingChecklist: "/임신중절수술-예약-전-확인사항",
  consultPrivacy: "/임신중절수술-상담-개인정보",
  medicationDisclosure: "/임신중절수술-상담-전-복용약-확인",
  painChange: "/임신중절수술-후-통증-변화",
  periodReturn: "/임신중절수술-후-생리",
  ovulationReturn: "/임신중절수술-후-배란-임신-가능성",
  contraceptionTiming: "/임신중절수술-후-피임-상담",
  emotionalChange: "/임신중절수술-후-감정-변화",
  minorConsult: "/미성년자-임신중절수술-상담",
  termsGlossary: "/임신중절수술-관련-용어-정리",
  preProcedureAnxiety: "/임신중절수술-전-심리적-부담",
  nextPregnancyPlanning: "/임신중절수술-후-다음-임신-계획",
  reliableInfoSources: "/임신중절수술-신뢰할-수-있는-정보-확인",
  recoveryJournal: "/임신중절수술-후-회복-기록",
  mythsFacts: "/임신중절수술-오해와-사실",
  decisionTakeTime: "/임신중절수술-상담-결정-미루기",
  partnerFamilyConsult: "/임신중절수술-상담-배우자-가족",
  infoHub: "/의료정보",
} as const;

/** 구 URL → 최종 한글 URL 308 permanent redirect */
export const LEGACY_REDIRECTS: Record<string, string> = {
  "/비용": ROUTES.cost,
  "/회복기간": ROUTES.recovery,
  "/주의사항": ROUTES.precautions,
  "/병원선택": ROUTES.hospital,
  "/후기": ROUTES.reviews,
  "/faq": ROUTES.faq,
  "/임신중절수술-병원선택": ROUTES.hospital,
  "/임신중절수술-자주묻는질문": ROUTES.faq,
};

export type RouteKey = keyof typeof ROUTES;
